# Generated by Django 5.0 on 2023-12-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duofitapp', '0002_exercicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceconfig',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
