# Generated by Django 5.0 on 2023-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duofitapp', '0003_exerciceconfig_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceconfig',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
