# Generated by Django 5.0 on 2023-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duofitapp', '0004_exerciceconfig_last_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciceconfig',
            name='last_training_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
