# Generated by Django 5.0 on 2023-12-31 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duofitapp', '0005_alter_exerciceconfig_last_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicelog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
