<<<<<<< HEAD
# Generated by Django 4.0.6 on 2024-01-05 08:48
=======
# Generated by Django 5.0 on 2024-01-03 08:37
>>>>>>> d77da84d47139c0f069eb156bd042e60b9e7d816

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duofitapp', '0007_alter_exercicelog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceconfig',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
